apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-app
  namespace: production
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: api
        image: hashicorp/http-echo:latest
        args:
          - "-text={\"status\":\"ok\",\"service\":\"backend-api\",\"message\":\"Microservices Architecture with GitOps Success!\"}"
        ports:
        - containerPort: 5678
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: production
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
  - port: 80
    targetPort: 5678
